### ISSUE TITLE
geigei 云闪付的cookie咋抓的

### ISSUE THREAD

**Issue by klxfp** [NaroisCool/naro-scripts#4]
geigei 云闪付的cookie咋抓的

**Comment by NaroisCool** [comment]
找到请求地址https://youhui.95516.com/newsign/api/daily_sign_in填到环境变量YSF

**Comment by Candy-yan1** [comment]
云闪付只要开了抓包软件  登录都登陆不上  有啥办法吗~~

**Comment by jiuchu** [comment]
> 找到请求地址[https://youhui.95516.com/newsign/api/daily_sign_in填到环境变量YSF](https://youhui.95516.com/newsign/api/daily_sign_in%E5%A1%AB%E5%88%B0%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8FYSF)
云闪付安卓抓包断网有办法吗

**Comment by NaroisCool** [comment]
似乎现在抓不到了，但是以前的抓到的现在还能用，也没过期

**Comment by NaroisCool** [comment]
已修复脚本
