### ISSUE TITLE
云闪付问题

### ISSUE THREAD

**Issue by SugarCarry** [NaroisCool/naro-scripts#7]
环境变量名称YSF
值:https://youhui.95516.com/newsign/api/daily_sign_in里面的全部cookie
运行结果:
{
  startedAt: '2024-06-07T00:00:00.000Z',
  days: [
    1, 1, 1, 0,
    0, 0, 0
  ],
  signedIn: true,
  repeated: true,
  signInDays: {
    days: 248,
    last: { date: '2024-05-31T15:59:59.999Z', days: 239 },
    current: {
      days: 9,
      end: '2024-06-09T00:00:00.000Z',
      start: '2024-06-01T00:00:00.000Z'
    }
  }
}

啥意思，这是成功还是没成功，页面也没签到成功呀。

**Comment by NaroisCool** [comment]
已修复
